import 'package:bot_md/Dashboard/home_.dart';
import 'package:bot_md/Dashboard/profile.dart';
import 'package:bot_md/constants.dart';
import 'package:bot_md/gps_location.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:get/get_navigation/src/extension_navigation.dart';
import 'package:get/state_manager.dart';
import 'package:google_fonts/google_fonts.dart';

RxMap currentUserData = RxMap({});
late DocumentSnapshot currentUser;
FirebaseAuth auth = FirebaseAuth.instance;
FirebaseMessaging messaging = FirebaseMessaging.instance;

List worldCountries_hopkins = [
  {"iso": "CHN", "name": "China"},
  {"iso": "TWN", "name": "Taipei and environs"},
  {"iso": "USA", "name": "US"},
  {"iso": "JPN", "name": "Japan"},
  {"iso": "THA", "name": "Thailand"},
  {"iso": "KOR", "name": "Korea, South"},
  {"iso": "SGP", "name": "Singapore"},
  {"iso": "PHL", "name": "Philippines"},
  {"iso": "MYS", "name": "Malaysia"},
  {"iso": "VNM", "name": "Vietnam"},
  {"iso": "AUS", "name": "Australia"},
  {"iso": "MEX", "name": "Mexico"},
  {"iso": "BRA", "name": "Brazil"},
  {"iso": "COL", "name": "Colombia"},
  {"iso": "FRA", "name": "France"},
  {"iso": "NPL", "name": "Nepal"},
  {"iso": "CAN", "name": "Canada"},
  {"iso": "KHM", "name": "Cambodia"},
  {"iso": "LKA", "name": "Sri Lanka"},
  {"iso": "CIV", "name": "Cote d'Ivoire"},
  {"iso": "DEU", "name": "Germany"},
  {"iso": "FIN", "name": "Finland"},
  {"iso": "ARE", "name": "United Arab Emirates"},
  {"iso": "IND", "name": "India"},
  {"iso": "ITA", "name": "Italy"},
  {"iso": "GBR", "name": "United Kingdom"},
  {"iso": "RUS", "name": "Russia"},
  {"iso": "SWE", "name": "Sweden"},
  {"iso": "ESP", "name": "Spain"},
  {"iso": "BEL", "name": "Belgium"},
  {"iso": "Others", "name": "Others"},
  {"iso": "EGY", "name": "Egypt"},
  {"iso": "IRN", "name": "Iran"},
  {"iso": "ISR", "name": "Israel"},
  {"iso": "LBN", "name": "Lebanon"},
  {"iso": "IRQ", "name": "Iraq"},
  {"iso": "OMN", "name": "Oman"},
  {"iso": "AFG", "name": "Afghanistan"},
  {"iso": "BHR", "name": "Bahrain"},
  {"iso": "KWT", "name": "Kuwait"},
  {"iso": "AUT", "name": "Austria"},
  {"iso": "DZA", "name": "Algeria"},
  {"iso": "HRV", "name": "Croatia"},
  {"iso": "CHE", "name": "Switzerland"},
  {"iso": "PAK", "name": "Pakistan"},
  {"iso": "GEO", "name": "Georgia"},
  {"iso": "GRC", "name": "Greece"},
  {"iso": "MKD", "name": "North Macedonia"},
  {"iso": "NOR", "name": "Norway"},
  {"iso": "ROU", "name": "Romania"},
  {"iso": "DNK", "name": "Denmark"},
  {"iso": "EST", "name": "Estonia"},
  {"iso": "NLD", "name": "Netherlands"},
  {"iso": "SMR", "name": "San Marino"},
  {"iso": "AZE", "name": "Azerbaijan"},
  {"iso": "BLR", "name": "Belarus"},
  {"iso": "ISL", "name": "Iceland"},
  {"iso": "LTU", "name": "Lithuania"},
  {"iso": "NZL", "name": "New Zealand"},
  {"iso": "NGA", "name": "Nigeria"},
  {"iso": "IRL", "name": "Ireland"},
  {"iso": "LUX", "name": "Luxembourg"},
  {"iso": "MCO", "name": "Monaco"},
  {"iso": "QAT", "name": "Qatar"},
  {"iso": "ECU", "name": "Ecuador"},
  {"iso": "CZE", "name": "Czechia"},
  {"iso": "ARM", "name": "Armenia"},
  {"iso": "DOM", "name": "Dominican Republic"},
  {"iso": "IDN", "name": "Indonesia"},
  {"iso": "PRT", "name": "Portugal"},
  {"iso": "AND", "name": "Andorra"},
  {"iso": "LVA", "name": "Latvia"},
  {"iso": "MAR", "name": "Morocco"},
  {"iso": "SAU", "name": "Saudi Arabia"},
  {"iso": "SEN", "name": "Senegal"},
  {"iso": "ARG", "name": "Argentina"},
  {"iso": "CHL", "name": "Chile"},
  {"iso": "JOR", "name": "Jordan"},
  {"iso": "UKR", "name": "Ukraine"},
  {"iso": "BLM", "name": "Saint Barthelemy"},
  {"iso": "HUN", "name": "Hungary"},
  {"iso": "FRO", "name": "Faroe Islands"},
  {"iso": "GIB", "name": "Gibraltar"},
  {"iso": "LIE", "name": "Liechtenstein"},
  {"iso": "POL", "name": "Poland"},
  {"iso": "TUN", "name": "Tunisia"},
  {"iso": "PSE", "name": "West Bank and Gaza"},
  {"iso": "BIH", "name": "Bosnia and Herzegovina"},
  {"iso": "SVN", "name": "Slovenia"},
  {"iso": "ZAF", "name": "South Africa"},
  {"iso": "BTN", "name": "Bhutan"},
  {"iso": "CMR", "name": "Cameroon"},
  {"iso": "CRI", "name": "Costa Rica"},
  {"iso": "PER", "name": "Peru"},
  {"iso": "SRB", "name": "Serbia"},
  {"iso": "SVK", "name": "Slovakia"},
  {"iso": "TGO", "name": "Togo"},
  {"iso": "VAT", "name": "Holy See"},
  {"iso": "GUF", "name": "French Guiana"},
  {"iso": "MLT", "name": "Malta"},
  {"iso": "MTQ", "name": "Martinique"},
  {"iso": "BGR", "name": "Bulgaria"},
  {"iso": "MDV", "name": "Maldives"},
  {"iso": "BGD", "name": "Bangladesh"},
  {"iso": "MDA", "name": "Moldova"},
  {"iso": "PRY", "name": "Paraguay"},
  {"iso": "ALB", "name": "Albania"},
  {"iso": "CYP", "name": "Cyprus"},
  {"iso": "BRN", "name": "Brunei"},
  {"iso": "MAC", "name": "Macao SAR"},
  {"iso": "MAF", "name": "Saint Martin"},
  {"iso": "BFA", "name": "Burkina Faso"},
  {"iso": "GGY-JEY", "name": "Channel Islands"},
  {"iso": "MNG", "name": "Mongolia"},
  {"iso": "PAN", "name": "Panama"},
  {"iso": "cruise", "name": "Cruise Ship"},
  {"iso": "TWN", "name": "Taiwan*"},
  {"iso": "BOL", "name": "Bolivia"},
  {"iso": "HND", "name": "Honduras"},
  {"iso": "COD", "name": "Congo (Kinshasa)"},
  {"iso": "JAM", "name": "Jamaica"},
  {"iso": "REU", "name": "Reunion"},
  {"iso": "TUR", "name": "Turkey"},
  {"iso": "CUB", "name": "Cuba"},
  {"iso": "GUY", "name": "Guyana"},
  {"iso": "KAZ", "name": "Kazakhstan"},
  {"iso": "CYM", "name": "Cayman Islands"},
  {"iso": "GLP", "name": "Guadeloupe"},
  {"iso": "ETH", "name": "Ethiopia"},
  {"iso": "SDN", "name": "Sudan"},
  {"iso": "GIN", "name": "Guinea"},
  {"iso": "ATG", "name": "Antigua and Barbuda"},
  {"iso": "ABW", "name": "Aruba"},
  {"iso": "KEN", "name": "Kenya"},
  {"iso": "URY", "name": "Uruguay"},
  {"iso": "GHA", "name": "Ghana"},
  {"iso": "JEY", "name": "Jersey"},
  {"iso": "NAM", "name": "Namibia"},
  {"iso": "SYC", "name": "Seychelles"},
  {"iso": "TTO", "name": "Trinidad and Tobago"},
  {"iso": "VEN", "name": "Venezuela"},
  {"iso": "CUW", "name": "Curacao"},
  {"iso": "SWZ", "name": "Eswatini"},
  {"iso": "GAB", "name": "Gabon"},
  {"iso": "GTM", "name": "Guatemala"},
  {"iso": "GGY", "name": "Guernsey"},
  {"iso": "MRT", "name": "Mauritania"},
  {"iso": "RWA", "name": "Rwanda"},
  {"iso": "LCA", "name": "Saint Lucia"},
  {"iso": "VCT", "name": "Saint Vincent and the Grenadines"},
  {"iso": "SUR", "name": "Suriname"},
  {"iso": "RKS", "name": "Kosovo"},
  {"iso": "CAF", "name": "Central African Republic"},
  {"iso": "COG", "name": "Congo (Brazzaville)"},
  {"iso": "GNQ", "name": "Equatorial Guinea"},
  {"iso": "UZB", "name": "Uzbekistan"},
  {"iso": "GUM", "name": "Guam"},
  {"iso": "PRI", "name": "Puerto Rico"},
  {"iso": "BEN", "name": "Benin"},
  {"iso": "GRL", "name": "Greenland"},
  {"iso": "LBR", "name": "Liberia"},
  {"iso": "MYT", "name": "Mayotte"},
  {"iso": "SOM", "name": "Somalia"},
  {"iso": "TZA", "name": "Tanzania"},
  {"iso": "BHS", "name": "Bahamas"},
  {"iso": "BRB", "name": "Barbados"},
  {"iso": "MNE", "name": "Montenegro"},
  {"iso": "GMB", "name": "Gambia"},
  {"iso": "KGZ", "name": "Kyrgyzstan"},
  {"iso": "MUS", "name": "Mauritius"},
  {"iso": "ZMB", "name": "Zambia"},
  {"iso": "DJI", "name": "Djibouti"},
  {"iso": "TCD", "name": "Chad"},
  {"iso": "SLV", "name": "El Salvador"},
  {"iso": "FJI", "name": "Fiji"},
  {"iso": "NIC", "name": "Nicaragua"},
  {"iso": "MDG", "name": "Madagascar"},
  {"iso": "HTI", "name": "Haiti"},
  {"iso": "AGO", "name": "Angola"},
  {"iso": "CPV", "name": "Cabo Verde"},
  {"iso": "NER", "name": "Niger"},
  {"iso": "PNG", "name": "Papua New Guinea"},
  {"iso": "ZWE", "name": "Zimbabwe"},
  {"iso": "TLS", "name": "Timor-Leste"},
  {"iso": "ERI", "name": "Eritrea"},
  {"iso": "UGA", "name": "Uganda"},
  {"iso": "DMA", "name": "Dominica"},
  {"iso": "GRD", "name": "Grenada"},
  {"iso": "MOZ", "name": "Mozambique"},
  {"iso": "SYR", "name": "Syria"},
  {"iso": "BLZ", "name": "Belize"},
  {"iso": "LAO", "name": "Laos"},
  {"iso": "LBY", "name": "Libya"},
  {"iso": "NA-SHIP-DP", "name": "Diamond Princess"},
  {"iso": "GNB", "name": "Guinea-Bissau"},
  {"iso": "MLI", "name": "Mali"},
  {"iso": "KNA", "name": "Saint Kitts and Nevis"},
  {"iso": "BWA", "name": "Botswana"},
  {"iso": "BDI", "name": "Burundi"},
  {"iso": "SLE", "name": "Sierra Leone"},
  {"iso": "MMR", "name": "Burma"},
  {"iso": "MWI", "name": "Malawi"},
  {"iso": "SSD", "name": "South Sudan"},
  {"iso": "ESH", "name": "Western Sahara"},
  {"iso": "STP", "name": "Sao Tome and Principe"},
  {"iso": "NA-SHIP-MSZ", "name": "MS Zaandam"},
  {"iso": "YEM", "name": "Yemen"},
  {"iso": "COM", "name": "Comoros"},
  {"iso": "TJK", "name": "Tajikistan"},
  {"iso": "LSO", "name": "Lesotho"},
  {"iso": "SLB", "name": "Solomon Islands"},
  {"iso": "MHL", "name": "Marshall Islands"},
  {"iso": "VUT", "name": "Vanuatu"},
  {"iso": "WSM", "name": "Samoa"},
  {"iso": "KIR", "name": "Kiribati"},
  {"iso": "PLW", "name": "Palau"},
  {"iso": "TON", "name": "Tonga"}
];

List worldCountries = [
  {"Country": "Afghanistan", "ThreeLetterSymbol": "afg"},
  {"Country": "Albania", "ThreeLetterSymbol": "alb"},
  {"Country": "Algeria", "ThreeLetterSymbol": "dza"},
  {"Country": "Andorra", "ThreeLetterSymbol": "and"},
  {"Country": "Angola", "ThreeLetterSymbol": "ago"},
  {"Country": "Anguilla", "ThreeLetterSymbol": "aia"},
  {"Country": "Antigua and Barbuda", "ThreeLetterSymbol": "atg"},
  {"Country": "Argentina", "ThreeLetterSymbol": "arg"},
  {"Country": "Armenia", "ThreeLetterSymbol": "arm"},
  {"Country": "Aruba", "ThreeLetterSymbol": "abw"},
  {"Country": "Australia", "ThreeLetterSymbol": "aus"},
  {"Country": "Austria", "ThreeLetterSymbol": "aut"},
  {"Country": "Azerbaijan", "ThreeLetterSymbol": "aze"},
  {"Country": "Bahamas", "ThreeLetterSymbol": "bhs"},
  {"Country": "Bahrain", "ThreeLetterSymbol": "bhr"},
  {"Country": "Bangladesh", "ThreeLetterSymbol": "bgd"},
  {"Country": "Barbados", "ThreeLetterSymbol": "brb"},
  {"Country": "Belarus", "ThreeLetterSymbol": "blr"},
  {"Country": "Belgium", "ThreeLetterSymbol": "bel"},
  {"Country": "Belize", "ThreeLetterSymbol": "blz"},
  {"Country": "Benin", "ThreeLetterSymbol": "ben"},
  {"Country": "Bermuda", "ThreeLetterSymbol": "bmu"},
  {"Country": "Bhutan", "ThreeLetterSymbol": "btn"},
  {"Country": "Bolivia", "ThreeLetterSymbol": "bol"},
  {"Country": "Bosnia and Herzegovina", "ThreeLetterSymbol": "bih"},
  {"Country": "Botswana", "ThreeLetterSymbol": "bwa"},
  {"Country": "Brazil", "ThreeLetterSymbol": "bra"},
  {"Country": "British Virgin Islands", "ThreeLetterSymbol": "vgb"},
  {"Country": "Brunei", "ThreeLetterSymbol": "brn"},
  {"Country": "Bulgaria", "ThreeLetterSymbol": "bgr"},
  {"Country": "Burkina Faso", "ThreeLetterSymbol": "bfa"},
  {"Country": "Burundi", "ThreeLetterSymbol": "bdi"},
  {"Country": "Cabo Verde", "ThreeLetterSymbol": "cpv"},
  {"Country": "Cambodia", "ThreeLetterSymbol": "khm"},
  {"Country": "Cameroon", "ThreeLetterSymbol": "cmr"},
  {"Country": "Canada", "ThreeLetterSymbol": "can"},
  {"Country": "CAR", "ThreeLetterSymbol": "caf"},
  {"Country": "Caribbean Netherlands", "ThreeLetterSymbol": "bes"},
  {"Country": "Cayman Islands", "ThreeLetterSymbol": "cym"},
  {"Country": "Chad", "ThreeLetterSymbol": "tcd"},
  {"Country": "Channel Islands", "ThreeLetterSymbol": "usa"},
  {"Country": "Chile", "ThreeLetterSymbol": "chl"},
  {"Country": "China", "ThreeLetterSymbol": "chn"},
  {"Country": "Colombia", "ThreeLetterSymbol": "col"},
  {"Country": "Comoros", "ThreeLetterSymbol": "com"},
  {"Country": "Congo", "ThreeLetterSymbol": "cog"},
  {"Country": "Costa Rica", "ThreeLetterSymbol": "cri"},
  {"Country": "Croatia", "ThreeLetterSymbol": "hrv"},
  {"Country": "Cuba", "ThreeLetterSymbol": "cub"},
  {"Country": "Curaçao", "ThreeLetterSymbol": "cuw"},
  {"Country": "Cyprus", "ThreeLetterSymbol": "cyp"},
  {"Country": "Czechia", "ThreeLetterSymbol": "cze"},
  {"Country": "Denmark", "ThreeLetterSymbol": "dnk"},
  {"Country": "Diamond Princess", "ThreeLetterSymbol": "usa"},
  {"Country": "Djibouti", "ThreeLetterSymbol": "dji"},
  {"Country": "Dominica", "ThreeLetterSymbol": "dma"},
  {"Country": "Dominican Republic", "ThreeLetterSymbol": "dom"},
  {"Country": "DRC", "ThreeLetterSymbol": "cod"},
  {"Country": "Ecuador", "ThreeLetterSymbol": "ecu"},
  {"Country": "Egypt", "ThreeLetterSymbol": "egy"},
  {"Country": "El Salvador", "ThreeLetterSymbol": "slv"},
  {"Country": "Equatorial Guinea", "ThreeLetterSymbol": "gnq"},
  {"Country": "Eritrea", "ThreeLetterSymbol": "eri"},
  {"Country": "Estonia", "ThreeLetterSymbol": "est"},
  {"Country": "Eswatini", "ThreeLetterSymbol": "swz"},
  {"Country": "Ethiopia", "ThreeLetterSymbol": "eth"},
  {"Country": "Faeroe Islands", "ThreeLetterSymbol": "fro"},
  {"Country": "Falkland Islands", "ThreeLetterSymbol": "flk"},
  {"Country": "Fiji", "ThreeLetterSymbol": "fji"},
  {"Country": "Finland", "ThreeLetterSymbol": "fin"},
  {"Country": "France", "ThreeLetterSymbol": "fra"},
  {"Country": "French Guiana", "ThreeLetterSymbol": "guf"},
  {"Country": "French Polynesia", "ThreeLetterSymbol": "pyf"},
  {"Country": "Gabon", "ThreeLetterSymbol": "gab"},
  {"Country": "Gambia", "ThreeLetterSymbol": "gmb"},
  {"Country": "Georgia", "ThreeLetterSymbol": "geo"},
  {"Country": "Germany", "ThreeLetterSymbol": "deu"},
  {"Country": "Ghana", "ThreeLetterSymbol": "gha"},
  {"Country": "Gibraltar", "ThreeLetterSymbol": "gib"},
  {"Country": "Greece", "ThreeLetterSymbol": "grc"},
  {"Country": "Greenland", "ThreeLetterSymbol": "grl"},
  {"Country": "Grenada", "ThreeLetterSymbol": "grd"},
  {"Country": "Guadeloupe", "ThreeLetterSymbol": "glp"},
  {"Country": "Guatemala", "ThreeLetterSymbol": "gtm"},
  {"Country": "Guinea", "ThreeLetterSymbol": "gin"},
  {"Country": "Guinea-Bissau", "ThreeLetterSymbol": "gnb"},
  {"Country": "Guyana", "ThreeLetterSymbol": "guy"},
  {"Country": "Haiti", "ThreeLetterSymbol": "hti"},
  {"Country": "Honduras", "ThreeLetterSymbol": "hnd"},
  {"Country": "Hong Kong", "ThreeLetterSymbol": "hkg"},
  {"Country": "Hungary", "ThreeLetterSymbol": "hun"},
  {"Country": "Iceland", "ThreeLetterSymbol": "isl"},
  {"Country": "India", "ThreeLetterSymbol": "ind"},
  {"Country": "Indonesia", "ThreeLetterSymbol": "idn"},
  {"Country": "Iran", "ThreeLetterSymbol": "irn"},
  {"Country": "Iraq", "ThreeLetterSymbol": "irq"},
  {"Country": "Ireland", "ThreeLetterSymbol": "irl"},
  {"Country": "Isle of Man", "ThreeLetterSymbol": "imn"},
  {"Country": "Israel", "ThreeLetterSymbol": "isr"},
  {"Country": "Italy", "ThreeLetterSymbol": "ita"},
  {"Country": "Ivory Coast", "ThreeLetterSymbol": "civ"},
  {"Country": "Jamaica", "ThreeLetterSymbol": "jam"},
  {"Country": "Japan", "ThreeLetterSymbol": "jpn"},
  {"Country": "Jordan", "ThreeLetterSymbol": "jor"},
  {"Country": "Kazakhstan", "ThreeLetterSymbol": "kaz"},
  {"Country": "Kenya", "ThreeLetterSymbol": "ken"},
  {"Country": "Kuwait", "ThreeLetterSymbol": "kwt"},
  {"Country": "Kyrgyzstan", "ThreeLetterSymbol": "kgz"},
  {"Country": "Laos", "ThreeLetterSymbol": "lao"},
  {"Country": "Latvia", "ThreeLetterSymbol": "lva"},
  {"Country": "Lebanon", "ThreeLetterSymbol": "lbn"},
  {"Country": "Lesotho", "ThreeLetterSymbol": "lso"},
  {"Country": "Liberia", "ThreeLetterSymbol": "lbr"},
  {"Country": "Libya", "ThreeLetterSymbol": "lby"},
  {"Country": "Liechtenstein", "ThreeLetterSymbol": "lie"},
  {"Country": "Lithuania", "ThreeLetterSymbol": "ltu"},
  {"Country": "Luxembourg", "ThreeLetterSymbol": "lux"},
  {"Country": "Macao", "ThreeLetterSymbol": "mac"},
  {"Country": "Madagascar", "ThreeLetterSymbol": "mdg"},
  {"Country": "Malawi", "ThreeLetterSymbol": "mwi"},
  {"Country": "Malaysia", "ThreeLetterSymbol": "mys"},
  {"Country": "Maldives", "ThreeLetterSymbol": "mdv"},
  {"Country": "Mali", "ThreeLetterSymbol": "mli"},
  {"Country": "Malta", "ThreeLetterSymbol": "mlt"},
  {"Country": "Marshall Islands", "ThreeLetterSymbol": "mhl"},
  {"Country": "Martinique", "ThreeLetterSymbol": "mtq"},
  {"Country": "Mauritania", "ThreeLetterSymbol": "mrt"},
  {"Country": "Mauritius", "ThreeLetterSymbol": "mus"},
  {"Country": "Mayotte", "ThreeLetterSymbol": "myt"},
  {"Country": "Mexico", "ThreeLetterSymbol": "mex"},
  {"Country": "Moldova", "ThreeLetterSymbol": "mda"},
  {"Country": "Monaco", "ThreeLetterSymbol": "mco"},
  {"Country": "Mongolia", "ThreeLetterSymbol": "mng"},
  {"Country": "Montenegro", "ThreeLetterSymbol": "mne"},
  {"Country": "Montserrat", "ThreeLetterSymbol": "msr"},
  {"Country": "Morocco", "ThreeLetterSymbol": "mar"},
  {"Country": "Mozambique", "ThreeLetterSymbol": "moz"},
  {"Country": "MS Zaandam", "ThreeLetterSymbol": "usa"},
  {"Country": "Myanmar", "ThreeLetterSymbol": "mmr"},
  {"Country": "Namibia", "ThreeLetterSymbol": "nam"},
  {"Country": "Nepal", "ThreeLetterSymbol": "npl"},
  {"Country": "Netherlands", "ThreeLetterSymbol": "nld"},
  {"Country": "New Caledonia", "ThreeLetterSymbol": "ncl"},
  {"Country": "New Zealand", "ThreeLetterSymbol": "nzl"},
  {"Country": "Nicaragua", "ThreeLetterSymbol": "nic"},
  {"Country": "Niger", "ThreeLetterSymbol": "ner"},
  {"Country": "Nigeria", "ThreeLetterSymbol": "nga"},
  {"Country": "North Macedonia", "ThreeLetterSymbol": "mkd"},
  {"Country": "Norway", "ThreeLetterSymbol": "nor"},
  {"Country": "Oman", "ThreeLetterSymbol": "omn"},
  {"Country": "Pakistan", "ThreeLetterSymbol": "pak"},
  {"Country": "Palestine", "ThreeLetterSymbol": "pse"},
  {"Country": "Panama", "ThreeLetterSymbol": "pan"},
  {"Country": "Papua New Guinea", "ThreeLetterSymbol": "png"},
  {"Country": "Paraguay", "ThreeLetterSymbol": "pry"},
  {"Country": "Peru", "ThreeLetterSymbol": "per"},
  {"Country": "Philippines", "ThreeLetterSymbol": "phl"},
  {"Country": "Poland", "ThreeLetterSymbol": "pol"},
  {"Country": "Portugal", "ThreeLetterSymbol": "prt"},
  {"Country": "Qatar", "ThreeLetterSymbol": "qat"},
  {"Country": "Réunion", "ThreeLetterSymbol": "reu"},
  {"Country": "Romania", "ThreeLetterSymbol": "rou"},
  {"Country": "Russia", "ThreeLetterSymbol": "rus"},
  {"Country": "Rwanda", "ThreeLetterSymbol": "rwa"},
  {"Country": "Saint Kitts and Nevis", "ThreeLetterSymbol": "kna"},
  {"Country": "Saint Lucia", "ThreeLetterSymbol": "lca"},
  {"Country": "Saint Martin", "ThreeLetterSymbol": "maf"},
  {"Country": "Saint Pierre Miquelon", "ThreeLetterSymbol": "spm"},
  {"Country": "San Marino", "ThreeLetterSymbol": "smr"},
  {"Country": "Sao Tome and Principe", "ThreeLetterSymbol": "stp"},
  {"Country": "Saudi Arabia", "ThreeLetterSymbol": "sau"},
  {"Country": "Senegal", "ThreeLetterSymbol": "sen"},
  {"Country": "Serbia", "ThreeLetterSymbol": "srb"},
  {"Country": "Seychelles", "ThreeLetterSymbol": "syc"},
  {"Country": "Sierra Leone", "ThreeLetterSymbol": "sle"},
  {"Country": "Singapore", "ThreeLetterSymbol": "sgp"},
  {"Country": "Sint Maarten", "ThreeLetterSymbol": "sxm"},
  {"Country": "S. Korea", "ThreeLetterSymbol": "kor"},
  {"Country": "Slovakia", "ThreeLetterSymbol": "svk"},
  {"Country": "Slovenia", "ThreeLetterSymbol": "svn"},
  {"Country": "Solomon Islands", "ThreeLetterSymbol": "slb"},
  {"Country": "Somalia", "ThreeLetterSymbol": "som"},
  {"Country": "South Africa", "ThreeLetterSymbol": "zaf"},
  {"Country": "South Sudan", "ThreeLetterSymbol": "ssd"},
  {"Country": "Spain", "ThreeLetterSymbol": "esp"},
  {"Country": "Sri Lanka", "ThreeLetterSymbol": "lka"},
  {"Country": "St. Barth", "ThreeLetterSymbol": "blm"},
  {"Country": "St. Vincent Grenadines", "ThreeLetterSymbol": "vct"},
  {"Country": "Sudan", "ThreeLetterSymbol": "sdn"},
  {"Country": "Suriname", "ThreeLetterSymbol": "sur"},
  {"Country": "Sweden", "ThreeLetterSymbol": "swe"},
  {"Country": "Switzerland", "ThreeLetterSymbol": "che"},
  {"Country": "Syria", "ThreeLetterSymbol": "syr"},
  {"Country": "Taiwan", "ThreeLetterSymbol": "twn"},
  {"Country": "Tajikistan", "ThreeLetterSymbol": "tjk"},
  {"Country": "Tanzania", "ThreeLetterSymbol": "tza"},
  {"Country": "Thailand", "ThreeLetterSymbol": "tha"},
  {"Country": "Timor-Leste", "ThreeLetterSymbol": "tls"},
  {"Country": "Togo", "ThreeLetterSymbol": "tgo"},
  {"Country": "Trinidad and Tobago", "ThreeLetterSymbol": "tto"},
  {"Country": "Tunisia", "ThreeLetterSymbol": "tun"},
  {"Country": "Turkey", "ThreeLetterSymbol": "tur"},
  {"Country": "Turks and Caicos", "ThreeLetterSymbol": "tca"},
  {"Country": "UAE", "ThreeLetterSymbol": "are"},
  {"Country": "Uganda", "ThreeLetterSymbol": "uga"},
  {"Country": "UK", "ThreeLetterSymbol": "gbr"},
  {"Country": "Ukraine", "ThreeLetterSymbol": "ukr"},
  {"Country": "Uruguay", "ThreeLetterSymbol": "ury"},
  {"Country": "USA", "ThreeLetterSymbol": "usa"},
  {"Country": "Uzbekistan", "ThreeLetterSymbol": "uzb"},
  {"Country": "Vanuatu", "ThreeLetterSymbol": "vut"},
  {"Country": "Vatican City", "ThreeLetterSymbol": "vat"},
  {"Country": "Venezuela", "ThreeLetterSymbol": "ven"},
  {"Country": "Vietnam", "ThreeLetterSymbol": "vnm"},
  {"Country": "Wallis and Futuna", "ThreeLetterSymbol": "wlf"},
  {"Country": "Western Sahara", "ThreeLetterSymbol": "esh"},
  {"Country": "Yemen", "ThreeLetterSymbol": "yem"},
  {"Country": "Zambia", "ThreeLetterSymbol": "zmb"},
  {"Country": "Zimbabwe", "ThreeLetterSymbol": "zwe"}
];

boxShad(double x, double y, double b, {opacity = 0.4}) {
  return BoxShadow(
    offset: Offset(x, y),
    blurRadius: b,
    color: secondaryColor.withOpacity(opacity),
  );
}

getPage(page) {
  switch (page) {
    case 'home':
      return {
        'type': 'index',
        'value': 1,
      };
    case 'profile':
      return {
        'type': 'index',
        'value': 2,
      };
    case 'settings':
      return {
        'type': 'index',
        'value': 2,
      };
  }
}

Widget montserratText(
    {text,
    weight = FontWeight.w700,
    double size = 21,
    align = TextAlign.center,
    color = const Color(0xff68B2A0)}) {
  return Text(
    text,
    style: GoogleFonts.montserrat(
      fontWeight: weight,
      fontSize: size,
      color: color,
    ),
    textAlign: align,
  );
}

gradientLongButton({text, onTap, double horizontal = 40}) {
  return InkWell(
    onTap: onTap,
    child: Container(
      margin: EdgeInsets.symmetric(horizontal: horizontal, vertical: 10),
      padding: const EdgeInsets.symmetric(vertical: 17),
      decoration: BoxDecoration(
        boxShadow: [boxShad(5, 5, 20)],
        borderRadius: BorderRadius.circular(21),
        gradient: LinearGradient(
          colors: [
            primaryColor,
            secondaryColor,
          ],
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
        ),
      ),
      child: Center(
        child: montserratText(
            text: text, size: 13, color: Colors.white, weight: FontWeight.w700),
      ),
    ),
  );
}

longButton({text, onTap, icon}) {
  return InkWell(
    onTap: onTap,
    child: Container(
      margin: EdgeInsets.symmetric(horizontal: 40, vertical: 10),
      padding: EdgeInsets.symmetric(vertical: 17),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [boxShad(5, 5, 20)],
        borderRadius: BorderRadius.circular(21),
      ),
      child: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            icon,
            SizedBox(
              width: 18,
            ),
            montserratText(
                text: text,
                size: 15,
                color: primaryColor,
                weight: FontWeight.w500)
          ],
        ),
      ),
    ),
  );
}

loginInputField(
    {hint, @required controller, hideText, double horizontal = 30}) {
  return Container(
    margin: EdgeInsets.symmetric(horizontal: horizontal),
    padding: EdgeInsets.symmetric(horizontal: 25, vertical: 10),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(21),
      color: Colors.white,
      boxShadow: [
        boxShad(0, 0, 50),
      ],
    ),
    child: TextField(
      autofocus: true,
      controller: controller,
      decoration: InputDecoration(
        border: InputBorder.none,
        hintText: hint,
        hintStyle: GoogleFonts.montserrat(color: Colors.grey.withOpacity(0.7)),
      ),
    ),
  );
}

Widget shadedListTile({title, subtitle, onTap}) {
  return Column(
    children: [
      Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          color: Colors.white,
          boxShadow: [
            boxShad(5, 7, 10, opacity: 0.15),
          ],
        ),
        child: ListTile(
          onTap: onTap,
          title: montserratText(
            text: title,
            color: Colors.black,
            align: TextAlign.start,
            size: 17,
          ),
          subtitle: montserratText(
            text: subtitle,
            size: 13,
            align: TextAlign.start,
            color: Colors.grey[500],
            weight: FontWeight.w400,
          ),
          trailing: const Icon(
            Icons.navigate_next_rounded,
            size: 30,
          ),
        ),
      ),
      SizedBox(
        height: 15,
      ),
    ],
  );
}

gradientAppBar({@required context, title}) {
  return Container(
    height: MediaQuery.of(context).size.height * 0.15,
    padding: EdgeInsets.symmetric(horizontal: 15),
    decoration: BoxDecoration(
      gradient: LinearGradient(
        colors: [primaryColor, secondaryColor],
        begin: Alignment.topLeft,
      ),
      boxShadow: [boxShad(5, 5, 25)],
      borderRadius: const BorderRadius.only(
        bottomLeft: Radius.circular(25),
        bottomRight: Radius.circular(25),
      ),
    ),
    child: Center(
      child: Row(
        children: [
          InkWell(
            onTap: () {
              Get.back();
            },
            child: const Icon(
              Icons.navigate_before,
              size: 30,
              color: Colors.white,
            ),
          ),
          const SizedBox(
            width: 15,
          ),
          montserratText(
            text: title,
            color: Colors.white,
            size: 20,
            weight: FontWeight.w500,
          ),
        ],
      ),
    ),
  );
}
